import React, { useState } from 'react';
import { SafeAreaView, KeyboardAvoidingView, ScrollView, View, Text, TextInput, TouchableOpacity, StyleSheet, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { salvarCartao } from '../database/queries';
import { useTema } from '../context/ThemeContext';

const BANDEIRAS = ['Visa', 'Mastercard', 'Elo', 'Hipercard', 'Outro'];
function formatarValor(texto) { const digitos = texto.replace(/\D/g, ''); return digitos ? (parseInt(digitos, 10) / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2 }) : ''; }

export default function AddCardScreen({ navigation }) {
  const { cores } = useTema();
  const [apelido, setApelido] = useState(''); const [bandeira, setBandeira] = useState('Visa'); const [ultimosDigitos, setUltimosDigitos] = useState(''); const [limite, setLimite] = useState(''); const [diaVencimento, setDiaVencimento] = useState(''); const [diaFechamento, setDiaFechamento] = useState(''); const [salvando, setSalvando] = useState(false);
  const diaValido = (dia) => parseInt(dia, 10) >= 1 && parseInt(dia, 10) <= 31;
  const podeSalvar = apelido.trim() && limite && diaValido(diaVencimento) && diaValido(diaFechamento) && !salvando;
  async function salvar() { if (!podeSalvar) return; setSalvando(true); try { await salvarCartao({ apelido: apelido.trim(), bandeira, ultimosDigitos: ultimosDigitos.replace(/\D/g, '').slice(-4), limite: parseFloat(limite.replace(/\./g, '').replace(',', '.')), diaVencimento: parseInt(diaVencimento, 10), diaFechamento: parseInt(diaFechamento, 10) }); navigation.goBack(); } finally { setSalvando(false); } }
  return <SafeAreaView style={[styles.container, { backgroundColor: cores.fundo }]}><KeyboardAvoidingView style={styles.teclado} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="close" size={24} color={cores.texto} /></TouchableOpacity><Text style={[styles.titulo, { color: cores.texto }]}>Novo cartão</Text><View style={{ width: 24 }} /></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={[styles.label, { color: cores.textoSecundario }]}>Apelido</Text><TextInput style={[styles.input, { borderColor: cores.borda, color: cores.texto }]} placeholder="Ex: Nubank, Itaú" value={apelido} onChangeText={setApelido} autoFocus /><Text style={[styles.label, { color: cores.textoSecundario }]}>Bandeira</Text><View style={styles.opcoes}>{BANDEIRAS.map((item) => <TouchableOpacity key={item} onPress={() => setBandeira(item)} style={[styles.opcao, { borderColor: cores.borda }, bandeira === item && { backgroundColor: cores.primario, borderColor: cores.primario }]}><Text style={[styles.opcaoTexto, { color: cores.texto }, bandeira === item && styles.opcaoTextoAtiva]}>{item}</Text></TouchableOpacity>)}</View><Text style={[styles.label, { color: cores.textoSecundario }]}>Últimos 4 dígitos <Text style={styles.opcional}>(opcional)</Text></Text><TextInput style={[styles.input, { borderColor: cores.borda, color: cores.texto }]} placeholder="0000" keyboardType="number-pad" maxLength={4} value={ultimosDigitos} onChangeText={setUltimosDigitos} /><Text style={[styles.label, { color: cores.textoSecundario }]}>Limite do cartão</Text><View style={[styles.valorLinha, { borderColor: cores.borda }]}><Text style={[styles.prefixo, { color: cores.textoSecundario }]}>R$</Text><TextInput style={[styles.valorInput, { color: cores.texto }]} placeholder="0,00" keyboardType="number-pad" value={limite} onChangeText={(texto) => setLimite(formatarValor(texto))} /></View><View style={styles.datas}><View style={styles.dataColuna}><Text style={[styles.label, { color: cores.textoSecundario }]}>Vencimento</Text><TextInput style={[styles.input, { borderColor: cores.borda, color: cores.texto }]} placeholder="Dia 10" keyboardType="number-pad" maxLength={2} value={diaVencimento} onChangeText={setDiaVencimento} /></View><View style={styles.dataColuna}><Text style={[styles.label, { color: cores.textoSecundario }]}>Fechamento</Text><TextInput style={[styles.input, { borderColor: cores.borda, color: cores.texto }]} placeholder="Dia 3" keyboardType="number-pad" maxLength={2} value={diaFechamento} onChangeText={setDiaFechamento} /></View></View></ScrollView><TouchableOpacity disabled={!podeSalvar} onPress={salvar} style={[styles.botao, { backgroundColor: cores.primario }, !podeSalvar && styles.desabilitado]}><Text style={styles.botaoTexto}>{salvando ? 'Salvando...' : 'Salvar cartão'}</Text></TouchableOpacity></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ container:{flex:1}, teclado:{flex:1,padding:16}, header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8}, titulo:{fontSize:16,fontWeight:'600'}, content:{flexGrow:1,paddingTop:18,paddingBottom:20}, label:{fontSize:13,marginBottom:7,marginTop:16}, opcional:{color:'#8A8A8E'}, input:{height:46,borderWidth:1,borderRadius:10,paddingHorizontal:12,fontSize:15}, opcoes:{flexDirection:'row',flexWrap:'wrap',gap:8}, opcao:{borderWidth:1,borderRadius:8,paddingHorizontal:13,paddingVertical:10}, opcaoTexto:{fontSize:13}, opcaoTextoAtiva:{color:'#fff'}, valorLinha:{height:46,borderWidth:1,borderRadius:10,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6},prefixo:{fontSize:16},valorInput:{flex:1,fontSize:16,padding:0},datas:{flexDirection:'row',gap:10},dataColuna:{flex:1}, botao:{height:48,borderRadius:10,alignItems:'center',justifyContent:'center'}, desabilitado:{backgroundColor:'#B7D3D0'}, botaoTexto:{color:'#fff',fontWeight:'600',fontSize:15} });