import React, { useState, useCallback } from 'react';
import { SafeAreaView, ScrollView, View, Text, TouchableOpacity, StyleSheet, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { getResumoCartoes } from '../database/queries';
import { useMes } from '../context/MonthContext';
import { useTema } from '../context/ThemeContext';
const real=(v)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const CORES_CARTAO = ['#1C1C1E', '#284B63', '#6B3E26', '#3F3B75'];
export default function CardsScreen({ navigation }) {
 const { referencia } = useMes();
 const { cores } = useTema();
 const [cartoes,setCartoes]=useState(null);
 useFocusEffect(useCallback(()=>{let ativo=true; getResumoCartoes(referencia).then(r=>ativo&&setCartoes(r)); return()=>{ativo=false};},[referencia]));
 if(!cartoes)return <SafeAreaView style={[styles.centro,{backgroundColor:cores.fundo}]}><ActivityIndicator size="large" color={cores.primario}/></SafeAreaView>;
 const totalCartoes=cartoes.reduce((soma,cartao)=>soma+cartao.total,0);
 return <SafeAreaView style={[styles.container,{backgroundColor:cores.fundo}]}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="arrow-back" size={22} color={cores.texto}/></TouchableOpacity><Text style={[styles.titulo,{color:cores.texto}]}>Cartões</Text><View style={{width:22}}/></View><ScrollView contentContainerStyle={styles.scroll}><View style={styles.resumo}><Text style={[styles.resumoLabel,{color:cores.textoSecundario}]}>Comprometido em cartões</Text><Text style={[styles.resumoValor,{color:cores.texto}]}>{real(totalCartoes)}</Text></View>{cartoes.length===0?<View style={styles.vazio}><Ionicons name="card-outline" size={36} color={cores.textoSecundario}/><Text style={[styles.vazioTitulo,{color:cores.texto}]}>Adicione seu primeiro cartão</Text><Text style={[styles.vazioTexto,{color:cores.textoSecundario}]}>Acompanhe parcelas, assinaturas e compras em um só lugar.</Text></View>:<View style={styles.pilha}>{cartoes.map((cartao,index)=><TouchableOpacity key={cartao.id} style={[styles.card,{backgroundColor:CORES_CARTAO[index%CORES_CARTAO.length],marginTop:index===0?0:-42,zIndex:cartoes.length-index}]} activeOpacity={0.86} onPress={()=>navigation.navigate('DetalhesCartao',{cartao})}><View style={styles.cardTopo}><Text style={styles.bandeira}>{cartao.bandeira}</Text><Ionicons name="card" size={25} color="rgba(255,255,255,0.85)"/></View><Text style={styles.numero}>{cartao.ultimos_digitos?`••••  ••••  ••••  ${cartao.ultimos_digitos}`:'••••  ••••  ••••  ••••'}</Text><View style={styles.cardRodape}><View><Text style={styles.cardLabel}>CARTÃO</Text><Text style={styles.nome}>{cartao.apelido}</Text></View><View style={styles.valorBloco}><Text style={styles.cardLabel}>NESTE MÊS</Text><Text style={styles.valor}>{real(cartao.total)}</Text></View></View></TouchableOpacity>)}</View>}</ScrollView><TouchableOpacity style={[styles.fab,{backgroundColor:cores.primario}]} onPress={()=>navigation.navigate('AdicionarCartao')}><Ionicons name="add" size={19} color="#fff"/><Text style={styles.fabTexto}>Adicionar cartão</Text></TouchableOpacity></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1},centro:{flex:1,alignItems:'center',justifyContent:'center'},header:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},titulo:{fontSize:16,fontWeight:'600'},scroll:{padding:16,paddingTop:0,paddingBottom:95},resumo:{marginBottom:20},resumoLabel:{fontSize:13},resumoValor:{fontSize:26,fontWeight:'700',marginTop:2},pilha:{paddingBottom:42},card:{height:188,borderRadius:20,padding:20,shadowColor:'#000',shadowOffset:{width:0,height:5},shadowOpacity:0.18,shadowRadius:10,elevation:5},cardTopo:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},bandeira:{fontSize:15,color:'#fff',fontWeight:'600'},numero:{color:'rgba(255,255,255,0.92)',fontSize:17,letterSpacing:1.2,marginTop:35},cardRodape:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginTop:20},cardLabel:{fontSize:9,color:'rgba(255,255,255,0.65)',letterSpacing:0.7},nome:{fontSize:15,color:'#fff',fontWeight:'600',marginTop:3},valorBloco:{alignItems:'flex-end'},valor:{fontSize:14,fontWeight:'600',color:'#fff',marginTop:3},vazio:{alignItems:'center',paddingTop:65,paddingHorizontal:30},vazioTitulo:{fontSize:16,fontWeight:'600',marginTop:12},vazioTexto:{fontSize:13,textAlign:'center',lineHeight:19,marginTop:6},fab:{position:'absolute',bottom:24,left:16,right:16,height:50,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},fabTexto:{color:'#fff',fontSize:15,fontWeight:'600'}});