import React, { useState } from 'react';
import { SafeAreaView, KeyboardAvoidingView, View, Text, TextInput, TouchableOpacity, StyleSheet, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { atualizarDadosCartao } from '../database/queries';
import { useTema } from '../context/ThemeContext';

function formatarValor(texto) { const digitos = texto.replace(/\D/g, ''); return digitos ? (parseInt(digitos, 10) / 100).toLocaleString('pt-BR', { minimumFractionDigits: 2 }) : ''; }
export default function EditCardScreen({ navigation, route }) {
  const { cores } = useTema();
  const { cartao } = route.params; const [limite, setLimite] = useState((cartao.limite || 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })); const [salvando, setSalvando] = useState(false);
  const podeSalvar = limite && parseFloat(limite.replace(/\./g, '').replace(',', '.')) >= 0 && !salvando;
  async function salvar() { if (!podeSalvar) return; setSalvando(true); try { await atualizarDadosCartao(cartao.id, { limite: parseFloat(limite.replace(/\./g, '').replace(',', '.')), diaVencimento: cartao.dia_vencimento, diaFechamento: cartao.dia_fechamento }); navigation.goBack(); } finally { setSalvando(false); } }
  return <SafeAreaView style={[styles.container, { backgroundColor: cores.fundo }]}><KeyboardAvoidingView style={styles.conteudo} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={styles.header}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="close" size={24} color={cores.texto} /></TouchableOpacity><Text style={[styles.titulo, { color: cores.texto }]}>Limite do cartão</Text><View style={{ width: 24 }} /></View><View style={styles.campo}><Text style={[styles.label, { color: cores.texto }]}>Limite disponível</Text><Text style={[styles.ajuda, { color: cores.textoSecundario }]}>Informe o limite total disponível no cartão.</Text><View style={[styles.valorLinha, { borderColor: cores.borda }]}><Text style={[styles.prefixo, { color: cores.textoSecundario }]}>R$</Text><TextInput style={[styles.input, { color: cores.texto }]} value={limite} onChangeText={(texto) => setLimite(formatarValor(texto))} keyboardType="number-pad" autoFocus /></View></View><TouchableOpacity style={[styles.botao, { backgroundColor: cores.primario }, !podeSalvar && styles.desabilitado]} disabled={!podeSalvar} onPress={salvar}><Text style={styles.botaoTexto}>{salvando ? 'Salvando...' : 'Salvar limite'}</Text></TouchableOpacity></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ container:{flex:1},conteudo:{flex:1,padding:16},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:8},titulo:{fontSize:16,fontWeight:'600'},campo:{flex:1,paddingTop:32},label:{fontSize:14,fontWeight:'600'},ajuda:{fontSize:13,marginTop:5},valorLinha:{height:52,borderWidth:1,borderRadius:10,paddingHorizontal:14,marginTop:16,flexDirection:'row',alignItems:'center',gap:7},prefixo:{fontSize:18},input:{flex:1,fontSize:20,fontWeight:'600',padding:0},botao:{height:48,borderRadius:10,alignItems:'center',justifyContent:'center'},desabilitado:{backgroundColor:'#B7D3D0'},botaoTexto:{fontSize:15,fontWeight:'600',color:'#fff'} });