import { ArrowRight, CreditCard, ShieldCheck } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Link, useOutletContext } from "react-router-dom";

import { Card as CardSurface } from "@/components/ui/card";
import type { FinanceLayoutContext } from "@/components/finance/FinanceShell";
import { formatBRL, getAccounts } from "@/lib/finance";

export default function Cards() {
  const { reference } = useOutletContext<FinanceLayoutContext>();
  const query = useQuery({ queryKey: ["finance-accounts", reference], queryFn: () => getAccounts(reference), enabled: Boolean(reference) });
  const cards = query.data?.cards ?? [];
  return <div className="space-y-7" data-testid="cards-page"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary" data-testid="cards-kicker">Limites e faturas</p><h1 className="mt-2 font-heading text-4xl font-semibold tracking-tight" data-testid="cards-title">Cartões</h1><p className="mt-3 text-sm text-muted-foreground" data-testid="cards-description">Abra um cartão para conferir todas as contas da fatura.</p></div><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3" data-testid="cards-grid">{query.isPending && <CardSurface className="h-56 animate-pulse border-border/70 bg-muted" data-testid="cards-loading" />}{cards.map((card) => <Link key={card.id} to={`/cartoes/${card.id}?month=${reference}`} className="group" data-testid={`open-card-${card.id}`}><CardSurface className="relative min-h-56 overflow-hidden border-slate-700 bg-slate-900 p-6 text-white shadow-xl transition-[transform,box-shadow,border-color] group-hover:-translate-y-1 group-hover:border-teal-400/60 group-hover:shadow-2xl" data-testid={`cards-list-item-${card.id}`}><div className="absolute -right-12 -top-16 size-44 rounded-full border-[22px] border-white/5" /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-teal-300" data-testid={`cards-list-brand-${card.id}`}>{card.brand}</p><h2 className="mt-2 font-heading text-2xl font-semibold" data-testid={`cards-list-name-${card.id}`}>{card.nickname}</h2></div><CreditCard className="size-6 text-teal-300" /></div><p className="mt-8 font-mono tracking-[0.22em] text-white/70" data-testid={`cards-list-number-${card.id}`}>•••• {card.last_four}</p><div className="mt-auto flex items-end justify-between pt-7"><div><p className="text-xs text-white/55" data-testid={`cards-list-invoice-label-${card.id}`}>Fatura atual</p><p className="mt-1 text-xl font-semibold" data-testid={`cards-list-invoice-${card.id}`}>{formatBRL(card.total)}</p></div><span className="flex items-center gap-1 text-sm text-teal-300" data-testid={`cards-list-action-${card.id}`}>Abrir fatura <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></div></div></CardSurface></Link>)}</section><div className="flex items-start gap-3 rounded-2xl border border-border/70 bg-card/70 p-4 text-sm text-muted-foreground" data-testid="cards-security-note"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" /><span data-testid="cards-security-text">Os cartões exibem apenas os dados necessários para organizar limites e vencimentos.</span></div></div>;
}