import { ArrowDownRight, ArrowUpRight, CalendarClock, CheckCircle2, ChevronRight, CircleAlert, Flag, ShoppingBag, WalletCards } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate, useOutletContext } from "react-router-dom";
import type { ReactNode } from "react";

import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { FinanceLayoutContext } from "@/components/finance/FinanceShell";
import { formatBRL, getGoals, getSummary } from "@/lib/finance";

function Stat({ label, value, icon, tone, testId, onClick }: { label: string; value: string; icon: ReactNode; tone: string; testId: string; onClick?: () => void }) {
  return <button type="button" onClick={onClick} className="text-left" data-testid={`${testId}-button`}><Card data-testid={testId} className="h-full border-border/70 bg-card/80 p-5 shadow-sm transition-[transform,box-shadow,border-color] hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-lg"><span className={`flex size-9 items-center justify-center rounded-xl ${tone}`} data-testid={`${testId}-icon`}>{icon}</span><p className="mt-5 font-heading text-2xl font-semibold tracking-tight" data-testid={`${testId}-value`}>{value}</p><p className="mt-1 text-xs text-muted-foreground" data-testid={`${testId}-label`}>{label}</p></Card></button>;
}

export default function Home() {
  const { reference, openTransaction } = useOutletContext<FinanceLayoutContext>();
  const navigate = useNavigate();
  const summaryQuery = useQuery({ queryKey: ["finance-summary", reference], queryFn: () => getSummary(reference), enabled: Boolean(reference) });
  const goalsQuery = useQuery({ queryKey: ["finance-goals"], queryFn: getGoals });
  const summary = summaryQuery.data;
  const goals = goalsQuery.data ?? [];

  return <div className="space-y-6" data-testid="home-page">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between" data-testid="home-heading-section"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-primary" data-testid="home-kicker">Seu dinheiro, com clareza</p><h1 className="mt-2 font-heading text-4xl font-semibold tracking-tight sm:text-5xl" data-testid="home-title">Um mês mais leve.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground" data-testid="home-description">Veja o que já aconteceu, o que vem pela frente e quanto realmente está livre para você.</p></div><Button type="button" onClick={openTransaction} className="gap-2 self-start sm:self-auto" data-testid="home-add-transaction-button"><ShoppingBag className="size-4" /> Lançar movimentação</Button></section>
    {summaryQuery.isPending && <div className="grid gap-4 lg:grid-cols-12" data-testid="home-loading"><div className="h-56 animate-pulse rounded-3xl bg-muted lg:col-span-8" /><div className="h-56 animate-pulse rounded-3xl bg-muted lg:col-span-4" /></div>}
    {summaryQuery.isError && <div className="rounded-2xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-700 dark:text-amber-300" data-testid="home-api-warning">Não foi possível carregar os dados deste mês. A estrutura do dashboard continua disponível.</div>}
    {summary && <>
      <section className="grid gap-5 lg:grid-cols-12" data-testid="home-bento-grid"><Card className="relative overflow-hidden border-emerald-400/30 bg-emerald-700 p-6 text-emerald-50 shadow-[0_30px_70px_-36px_rgba(13,148,136,0.9)] sm:p-8 lg:col-span-8" data-testid="saldo-livre-real-card"><div className="absolute -right-20 -top-24 size-72 rounded-full border-[28px] border-white/10" /><div className="relative"><div className="flex items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-emerald-100/70" data-testid="saldo-livre-real-label">Saldo Livre Real</p><p className="mt-4 font-mono text-4xl font-semibold tracking-tight sm:text-5xl" data-testid="saldo-livre-real-value">{formatBRL(summary.saldo_livre_real)}</p><p className="mt-3 max-w-md text-sm leading-6 text-emerald-100/80" data-testid="saldo-livre-real-description">Valor seguro para gastar depois de descontar as contas previstas e os compromissos do mês.</p></div><span className="hidden size-12 items-center justify-center rounded-2xl bg-white/10 sm:flex" data-testid="saldo-livre-real-icon"><WalletCards className="size-6" /></span></div><div className="mt-8 flex flex-wrap items-center gap-3"><Button type="button" variant="secondary" onClick={openTransaction} className="gap-2" data-testid="saldo-livre-real-action">Adicionar lançamento <ChevronRight className="size-4" /></Button><span className="text-xs text-emerald-100/75" data-testid="saldo-livre-real-month">Período: {summary.reference}</span></div></div></Card><Card className="border-border/70 bg-card/85 p-6 lg:col-span-4" data-testid="monthly-balance-card"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground" data-testid="monthly-balance-label">Saldo disponível</p><p className="mt-3 font-heading text-3xl font-semibold tracking-tight" data-testid="saldo-disponivel-value">{formatBRL(summary.saldo_disponivel)}</p></div><span className="flex size-10 items-center justify-center rounded-xl bg-primary/10 text-primary" data-testid="monthly-balance-icon"><WalletCards className="size-5" /></span></div><div className="mt-8 space-y-3 border-t border-border/70 pt-4"><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground" data-testid="monthly-balance-entered-label">Entrou</span><strong className="text-emerald-600" data-testid="monthly-balance-entered-value">{formatBRL(summary.entrou)}</strong></div><div className="flex items-center justify-between text-sm"><span className="text-muted-foreground" data-testid="monthly-balance-spent-label">Gasto</span><strong data-testid="monthly-balance-spent-value">{formatBRL(summary.gasto)}</strong></div></div></Card></section>
      <section className="grid grid-cols-2 gap-4 lg:grid-cols-4" data-testid="home-stats-grid"><Stat label="Entradas no mês" value={formatBRL(summary.entrou)} icon={<ArrowUpRight className="size-4" />} tone="bg-emerald-500/12 text-emerald-600" testId="stat-entrou" onClick={() => navigate("/contas?tab=entradas")} /><Stat label="Gastos no mês" value={formatBRL(summary.gasto)} icon={<ArrowDownRight className="size-4" />} tone="bg-rose-500/12 text-rose-600" testId="stat-gasto" onClick={() => navigate("/contas")} /><Stat label="Contas previstas" value={formatBRL(summary.previsto)} icon={<CalendarClock className="size-4" />} tone="bg-amber-500/12 text-amber-600" testId="stat-previsto" onClick={() => navigate("/planejamento")} /><Stat label="Guardado em metas" value={formatBRL(summary.total_metas)} icon={<Flag className="size-4" />} tone="bg-primary/12 text-primary" testId="total-metas" /></section>
      <section className="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(300px,0.7fr)]" data-testid="home-lower-grid"><Card className="border-border/70 bg-card/80 p-6" data-testid="home-payment-card"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-emerald-500/12 text-emerald-600" data-testid="paid-accounts-icon"><CheckCircle2 className="size-5" /></span><div><p className="text-sm text-muted-foreground" data-testid="paid-accounts-label">Contas marcadas como pagas</p><p className="mt-1 font-heading text-2xl font-semibold" data-testid="paid-accounts-value">{formatBRL(summary.contas_pagas)}</p></div></div><div className="mt-6 rounded-2xl bg-amber-500/10 p-4 text-sm text-amber-700 dark:text-amber-300"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 size-4 shrink-0" /><span data-testid="forecast-alert-text">Continuando nesse ritmo, seu saldo livre no fim do mês fica em torno de {formatBRL(summary.alerta_previsao)}.</span></div></div></Card><Card className="border-border/70 bg-card/80 p-6" data-testid="home-goal-preview-card"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-primary" data-testid="goal-preview-kicker">Metas</p><h2 className="mt-2 font-heading text-xl font-semibold" data-testid="goal-preview-title">O que você está construindo</h2></div><Flag className="size-5 text-primary" /></div>{goals.slice(0, 1).map((goal) => { const progress = goal.target_value ? Math.min(goal.saved_value / goal.target_value, 1) : 0; return <div key={goal.id} className="mt-6" data-testid="goal-preview-item"><div className="flex items-center justify-between text-sm"><span data-testid="goal-preview-name">{goal.name}</span><span className="font-mono text-xs text-muted-foreground" data-testid="goal-preview-percent">{Math.round(progress * 100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted" data-testid="goal-preview-track"><div className="h-full rounded-full bg-primary" style={{ width: `${progress * 100}%` }} data-testid="goal-preview-progress" /></div><p className="mt-3 text-xs text-muted-foreground" data-testid="goal-preview-amount">{formatBRL(goal.saved_value)} de {formatBRL(goal.target_value)}</p></div>; })}<button type="button" onClick={() => toastGoal(navigate)} className="mt-5 flex items-center gap-1 text-sm font-medium text-primary transition-[gap] hover:gap-2" data-testid="goal-preview-link">Ver metas <ChevronRight className="size-4" /></button></Card></section>
    </>}
  </div>;
}

function toastGoal(navigate: ReturnType<typeof useNavigate>) {
  navigate("/");
}